import type { Metadata } from "next";
import { Chewy } from "next/font/google";
import "./globals.css";
export const dynamic = 'force-dynamic';

const fontChewy = Chewy({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-headline',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-scroll-behavior="smooth">
      <body
        className={`${fontChewy.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
